apiVersion: v1
kind: Namespace
metadata:
  name: osc-labeler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osc-labeler
  namespace: osc-labeler
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osc-labeler-role
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "patch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osc-labeler-binding
subjects:
  - kind: ServiceAccount
    name: osc-labeler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: osc-labeler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: osc-labeler
  name: osc-labeler
  namespace: osc-labeler
spec:
  selector:
    matchLabels:
      app: osc-labeler
  template:
    metadata:
      labels:
        app: osc-labeler
    spec:
      serviceAccountName: osc-labeler
      containers:
        - name: osc-labeler
          image: outscale/cloud-provider-osc:v1.32.4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/osc-labeler
            - --wait
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"

