apiVersion: v1
kind: Namespace
metadata:
  name: "access-logs"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoheaders
  namespace: access-logs
  labels:
    app: echoheaders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoheaders
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-lb-public
  namespace: access-logs
  labels:
    app: echoheaders
  annotations:
    service.beta.kubernetes.io/osc-load-balancer-name: "access-logs-test"
    service.beta.kubernetes.io/osc-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/osc-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/osc-load-balancer-access-log-oos-bucket-name: "my-ccm-examples"
    service.beta.kubernetes.io/osc-load-balancer-access-log-oos-bucket-prefix: "access-logs"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoheaders
  type: LoadBalancer

