apiVersion: v1
kind: Secret
metadata:
  name: osc-secret
  namespace: kube-system
stringData:
  key_id: 39MG8AVXG0I6T1BZL1LJ
  access_key: GE4HZQC0LJC23GL5SP69AJ9XG6UQXYNJ3XLPSANX
  aws_default_region: eu-west-2
  aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
  osc_account_id: MY_OSC_ACCOUNT_ID
  osc_account_iam: MY_OSC_ACCOUNT_IAM
  osc_user_id: MY_OSC_USER_ID
  osc_arn: MY_OSC_ARN
