apiVersion: v1
kind: Secret
metadata:
  name: osc-secret
  namespace: kube-system
stringData:
  key_id: 39MG8AVXG0I6T1BZL1LJ
  access_key: GE4HZQC0LJC23GL5SP69AJ9XG6UQXYNJ3XLPSANX
  aws_default_region: eu-west-2
