apiVersion: v1
kind: Secret
metadata:
  name: osc-secret
  namespace: kube-system
stringData:
  key_id: MY_AWS_ACCESS_KEY_ID
  access_key: MY_AWS_SECRET_ACCESS_KEY
  aws_default_region: MY_AWS_DEFAULT_REGION
  aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
  osc_account_id: MY_OSC_ACCOUNT_ID
  osc_account_iam: MY_OSC_ACCOUNT_IAM
  osc_user_id: MY_OSC_USER_ID
  osc_arn: MY_OSC_ARN