apiVersion: v1
kind: Namespace
metadata:
  name: "multiaz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoheaders
  namespace: multiaz
  labels:
    app: echoheaders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoheaders
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-lb-public
  namespace: multiaz
  labels:
    app: echoheaders
  annotations:
    service.beta.kubernetes.io/osc-load-balancer-instances: "2"
    service.beta.kubernetes.io/osc-load-balancer-name: "multiaz-a,multiaz-b"
    service.beta.kubernetes.io/osc-load-balancer-subregions: "eu-west-2-a,eu-west-2-b"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoheaders
  type: LoadBalancer

