# Default values for osc-cloud-controller-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas to deploy
replicaCount: 1

image:
  # -- Container image to use
  repository: outscale/cloud-provider-osc
  # -- Container image tag to deploy
  tag: v0.2.1
  # -- Container pull policy
  pullPolicy: IfNotPresent

# -- Verbosity level of the plugin
verbose: 5
# -- Secret name containing cloud credentials
oscSecretName: osc-secret
# -- Specify image pull secrets
imagePullSecrets: []
# -- Labels for pod
podLabels: {}

# -- Assign Pod to Nodes (see [kubernetes doc](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/))
nodeSelector: {}
# -- Pod tolerations (see [kubernetes doc](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/))
tolerations: []
