# Default values for osc-cloud-controller-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas to deploy
replicaCount: 1
# -- Use customEndpoint (url with protocol) ex: https://api.eu-west-2.outscale.com/api/v1
customEndpoint: ""
# -- Use customEndpointFcu (url with protocol) ex: https://fcu.eu-west-2.outscale.com
customEndpointFcu: ""
# -- Use customEndpointLbu (url with protocol) ex: https://lbu.eu-west-2.outscale.com  
customEndpointLbu: ""
# -- Use customEndpointEim (url with protocol) ex: https://eim.eu-west-2.outscale.com    
customEndpointEim: ""
image:
  # -- Container image to use
  repository: outscale/cloud-provider-osc
  # -- Container image tag to deploy
  tag: v0.2.8
  # -- Container pull policy
  pullPolicy: IfNotPresent

# -- Verbosity level of the plugin
verbose: 5
# -- Secret name containing cloud credentials
oscSecretName: osc-secret
# -- Set if credentials are read from a [profile file](https://docs.outscale.com/en/userguide/Installing-and-Configuring-oapi-cli.html#_configuring_oapi_cli) stored in `/root/.osc/config.json`. If `oscSecretName` is set, the secret is mounted as `/root/.osc` and is expected to have a `config.json` key.
oscCredentialsFromFile: false
# -- Specify image pull secrets
imagePullSecrets: []
# -- Labels for pod
podLabels: {}

# -- Assign Pod to Nodes (see [kubernetes doc](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/))
nodeSelector: {}
# -- Assign Pod to Nodes (see [kubernetes doc](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/))
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
# -- Pod tolerations (see [kubernetes doc](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/))
tolerations:
# this taint is set by all kubelets running `--cloud-provider=external`
# so we should tolerate it to schedule the CCM
# and allow CCM to provide info required for initialization.
- key: node.cloudprovider.kubernetes.io/uninitialized
  value: "true"
  effect: NoSchedule
# cloud controller manager should be able to run on control-plane nodes
- key: node-role.kubernetes.io/control-plane
  effect: NoSchedule

caBundle:
  # -- Secret name containing additional certificates authorities
  name: ''
  # -- Entry key in secret used to store additional certificates authorities
  key: ''

# -- Value used to create environment variable HTTPS_PROXY
httpsProxy: ''
# -- Value used to create environment variable NO_PROXY
noProxy: ''

# resources -- Pod resource requests and limits.
resources: {}

# Extra tags to set on every created load-balancer.
# extraLoadBalancerTags:
#   key1: value1
#   key2: value2
# -- Add extra tags on load-balancers
extraLoadBalancerTags: {}

# -- Set this if you want to use a specific cluster ID instead of the automatically computed one. Use with caution.
customClusterID: ''
