name: Build

on:
  push:
    branches:
      - kubernetes-*
  pull_request:
    branches:
      - main
      - kubernetes-*
    paths:
      - "**.go"
      - "Dockerfile"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "deploy/**"
      - "!tests/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: 🔎 Docker Lint
      run: bash -c "make dockerlint"
    - name: 🔎 golangci-lint
      uses: outscale/goutils/.github/actions/lint@bd54158ec41d8d18182eb99e516353ed5ea92858 # v1.0.1
    - name: 🔎 Reuse check
      run: make lint-reuse
      shell: bash
    - name: Test
      run: bash -c "make test"
    - name: 🔎 Check docs
      run: bash -c "make check-helm-docs"
    - name: 🔎 Check manifest
      run: bash -c "make check-helm-manifest"
