name: Build

on:
  push:
    branches:
      - kubernetes-*
  pull_request:
    branches:
      - main
      - kubernetes-*
    paths:
      - "**.go"
      - "Dockerfile"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "deploy/**"
      - "!tests/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: 🔎 Docker Lint
      run: bash -c "make dockerlint"
    - name: 🔎 golangci-lint
      uses: outscale/goutils/.github/actions/lint@05ad7817324ae08f446039cbe11ed0322ae2467b # main
    - name: 🔎 Reuse check
      run: make lint-reuse
      shell: bash
    - name: Test
      run: bash -c "make test"
    - name: Image
      run: bash -c "make build-image"
    - name: 🔎 Check docs
      run: bash -c "make check-helm-docs"
    - name: 🔎 Check manifest
      run: bash -c "make check-helm-manifest"
