name: E2E

on:
  push:
    branches:
      - kubernetes-*
  pull_request:
    branches:
      - main
      - kubernetes-*
    paths:
      - "**.go"
      - "Dockerfile"
      - "Makefile"
      - "go.*"
      - "deploy/k8s-osc-ccm/**.yaml"
      - ".github/workflows/e2e_test.yml"
      - ".github/local_action/start_ccm_e2e/action.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    runs-on: [self-hosted, linux]
    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: ⬇️ Install kubectl
      uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
      with:
        version: v1.34.9
    - name: ⬇️ Install Helm
      uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      with:
        version: v4.2.3
    - name: ⬇️ Install Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: ⬇️ Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
    - name: 🔐 Set AK/SK name based on runner region
      run: .github/scripts/runneraksk.sh
    - name: ⬇️ Install octl
      uses: outscale/octl/.github/actions/setup_octl@1611a6d99b4017e59a3a5d755fdbf0147ac070e8 # v0.0.31
      with:
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@1a8eba5199913da60ae6d92d6050e17410186a38 # v0.16.1+hotfix.0
      with:
        access_key: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        secret_key: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        region: ${{ env.OSC_REGION }}
        exclude_resource_types: access_key
    - name: 🐳 Login to Harbor
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ${{ vars.REGISTRY }}
        username: admin
        password: ${{ secrets.HARBOR_ADMIN_PASSWORD }}
    - name: 📦 Run GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        version: 'v2.15.4'
        args: release --clean --snapshot
    - name: 📦 Push the Docker image
      run: |
        make image-tag image-push
      env:
        IMAGE: "outscale/cloud-provider-osc"
        IMAGE_TAG: "${{ github.sha }}-amd64"
        REGISTRY_IMAGE: "${{ vars.REGISTRY }}/outscale/cloud-provider-osc"
        REGISTRY_TAG: ${{ github.sha }}

    - name: 👷 Deploy Cluster
      id: caposc
      uses: outscale/cluster-api-provider-outscale/.github/actions/deploy_cluster@f505cfa8d2bcc452b7a733879f27307859188ed3 # v1.5
      with:
        RUNNER_NAME: ${{ runner.name }}
        OKS_ACCESS_KEY: ${{ secrets.OKS_ACCESS_KEY }}
        OKS_SECRET_KEY: ${{ secrets.OKS_SECRET_KEY }}
        OKS_REGION: ${{ vars.OKS_REGION }}
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CLUSTER_NAME: "ccm"
        IMAGE_NAME: ${{ vars.OMI_NAME }}
        WORKER_COUNT: 2
        CCM: "false"
    - name: 🔎 Fetch Cluster ID
      id: clusterid
      run: |
        cid=`kubectl get -n ccm osccluster.infrastructure.cluster.x-k8s.io/ccm -o json | jq -r '.metadata.labels."outscale.com/clusterUID"'`
        echo "clusterid=$cid" | tee $GITHUB_OUTPUT
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.MANAGEMENT_KUBECONFIG }}"
    - name: 🔐 Configure credentials
      run: |
        octl kube secret --name osc-secret | kubectl apply -f -
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
    - name: 👷 Install CCM
      run: |
        echo "installing CCM"
        helm install --wait k8s-osc-ccm deploy/k8s-osc-ccm --set oscSecretName=osc-secret --set image.repository=${{ vars.REGISTRY }}/outscale/cloud-provider-osc --set oscSecretFormat=v1 --set image.tag=${{ github.sha }} \
          --set extraLoadBalancerTags.clikey=clivalue --set "extraNodeLabels.clilabel=\{\{ .SubRegion \}\}" --set verbose=6
        echo "waiting for worker nodes"
        kubectl wait --for=condition=Ready nodes --all --timeout=900s
        kubectl get nodes -o wide
        echo "waiting for pods"
        kubectl wait --for=condition=Ready po --all -A --timeout=900s
        kubectl get po -A
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
    - name: 🧪 Run e2e tests
      id: e2etest
      run: |
        make e2etest
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CCM_IMAGE: "${{ vars.REGISTRY }}/outscale/cloud-provider-osc:${{ github.sha }}"
    - name: 👷 Reconfigure CCM in remote mode
      id: setupremote
      run: |
        echo "updating CCM config"
        helm upgrade --wait k8s-osc-ccm deploy/k8s-osc-ccm --set oscSecretName=osc-secret --set image.repository=${{ vars.REGISTRY }}/outscale/cloud-provider-osc --set image.tag=${{ github.sha }}\
          --set extraLoadBalancerTags.clikey=clivalue --set "extraNodeLabels.clilabel=\{\{ .SubRegion \}\}" --set remote=true --set customClusterID=$CLUSTER_ID --set verbose=6
        sleep 5
        kubectl get pod -n kube-system -l "app=osc-cloud-controller-manager"
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CLUSTER_ID: ${{ steps.clusterid.outputs.clusterid }}
    - name: 🧪 Run e2e tests in remote mode
      id: e2remote
      run: |
        E2E_FOCUS=fast make e2etest
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
    - name: 👷 Reconfigure CCM with credentials in profile file
      run: |
        profile="{\"default\":{\"access_key\":\"${{ secrets[env.OSC_ACCESS_KEY_NAME] }}\",\"secret_key\":\"${{ secrets[env.OSC_SECRET_KEY_NAME] }}\"}}"
        kubectl create secret generic osc-secret-file --from-literal=config.json=$profile -n kube-system
        echo "updating CCM config"
        helm upgrade --wait k8s-osc-ccm deploy/k8s-osc-ccm --set oscSecretName=osc-secret-file --set oscCredentialsFromFile=true --set image.repository=${{ vars.REGISTRY }}/outscale/cloud-provider-osc --set image.tag=${{ github.sha }}\
          --set extraLoadBalancerTags.clikey=clivalue --set "extraNodeLabels.clilabel=\{\{ .SubRegion \}\}" --set verbose=6
        sleep 5
        kubectl get pod -n kube-system -l "app=osc-cloud-controller-manager"
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
    - name: 🧪 Run e2e tests with credentials in profile file
      id: e2eprofile
      run: |
        E2E_FOCUS=fast make e2etest
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
    - name: 📝 Get CCM logs
      run: |
        kubectl logs -l app=osc-cloud-controller-manager -n kube-system --tail=-1 | grep -v "successfully renewed lease"
      if: ${{ failure() }}
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
