# Github action for releasing the binaries
name: release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:  

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changelog for release
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          path: "docs/CHANGELOG.md"
          version: ${{ github.ref_name }}
      - uses: azure/setup-helm@v4
        with:
          version: v3.18.3
      - name : Create Helm-package
        run: make helm-package
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          body: ${{ steps.changelog.outputs.changes }}
          files: out-helm/*